services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    image: backend:latest
    container_name: backend
    env_file:
      - env/user.env
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ../backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.dockerfile
    image: frontend:latest
    container_name: frontend
    env_file:
      - env/user.env
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ../frontend:/app
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://localhost:${BACKEND_PORT}

networks:
  app-network:
    name: network
    driver: bridge
